BookStoreWebsite/src/com/bookstore/entity/BookOrder.java
package com.bookstore.entity;
// default package
// Generated Sep 2, 2020, 8:57:07 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "BookOrder.findAll", query = "SELECT bo FROM BookOrder bo ORDER BY bo.orderDate DESC"),
	@NamedQuery(name = "BookOrder.countAll", query = "SELECT COUNT(*) FROM BookOrder"),
	@NamedQuery(name = "BookOrder.findByCustomer", query = "SELECT bo FROM BookOrder bo WHERE bo.customer.customerId =:customerId ORDER BY bo.orderDate DESC"),
	@NamedQuery(name = "BookOrder.findByIdAndCustomer", query = "SELECT bo FROM BookOrder bo WHERE bo.customer.customerId =:customerId AND bo.orderId =:orderId"),
	@NamedQuery(name = "BookOrder.countByCustomer", query = "SELECT COUNT(bo.orderId) FROM BookOrder bo WHERE bo.customer.customerId =:customerId"),
})
@Table(name = "book_order", catalog = "heroku_4843a9412bf1c66")
public class BookOrder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer orderId;
	private Customer customer;
	private Date orderDate;
	private String addressLine1;
	private String addressLine2;
	private String firstname;
	private String lastname;
	private String phone;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String paymentMethod;
	private float shippingFee;
	private float tax;
	private float subtotal;
	private float total;
	private String status;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public BookOrder() {
	}

	public BookOrder(Customer customer, Date orderDate, String addressLine1, String addressLine2, String firstname, String lastname,
			String phone, String city, String state, String zipcode, String country, String paymentMethod, float shippingFee, float tax, float subtotal, float total, String status) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.paymentMethod = paymentMethod;
		this.shippingFee = shippingFee;
		this.tax = tax;
		this.subtotal = subtotal;
		this.total = total;
		this.status = status;
	}

	public BookOrder(Customer customer, Date orderDate, String addressLine1, String addressLine2, String firstname, String lastname,
			String phone, String city, String state, String zipcode, String country, String paymentMethod, float shippingFee, float tax, float subtotal, float total, String status, Set<OrderDetail> orderDetails) {
		this(customer,orderDate,addressLine1,addressLine2,firstname,lastname,phone,city,state,zipcode,country,paymentMethod,shippingFee,tax,subtotal,total,status);
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "r_address_line1", nullable = false, length = 256)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "r_address_line2", nullable = false, length = 256)
	public String getAddressLine2() {
		return addressLine2;
	}
	
	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "r_firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}
	
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	
	@Column(name = "r_lastname", nullable = false, length = 30)
	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "r_phone", nullable = false, length = 15)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "r_city", nullable = false, length = 32)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "r_state", nullable = false, length = 45)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "r_zipcode", nullable = false, length = 24)
	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "r_country", nullable = false, length = 4)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	@Transient
	public String getCountryName() {
		return new Locale("", this.country).getDisplayCountry();
	}

	@Column(name = "shipping_fee", nullable = false, precision = 12, scale = 0)
	public float getShippingFee() {
		return shippingFee;
	}

	public void setShippingFee(float shippingFee) {
		this.shippingFee = shippingFee;
	}

	@Column(name = "tax", nullable = false, precision = 12, scale = 0)
	public float getTax() {
		return tax;
	}

	public void setTax(float tax) {
		this.tax = tax;
	}

	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "payment_method", nullable = false, length = 20)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "total", nullable = false, precision = 12, scale = 0)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bookOrder", cascade=CascadeType.ALL, orphanRemoval = true)
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}
	
	@Transient
	public int getBookCopies() {
		int total=0;
		for (OrderDetail orderDetail : orderDetails) {
			total += orderDetail.getQuantity();
		}
		
		return total;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BookOrder other = (BookOrder) obj;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		return true;
	}

}

BookStoreWebsite/src/com/bookstore/entity/Customer.java
package com.bookstore.entity;
// Generated Jul 30, 2020, 6:48:24 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "Customer.findAll", query = "SELECT c FROM Customer c ORDER BY c.registerDate DESC"),
	@NamedQuery(name = "Customer.findByEmail", query = "SELECT c FROM Customer c WHERE c.email = :email"),
	@NamedQuery(name = "Customer.countAll", query = "SELECT Count(c.email) FROM Customer c"),
	@NamedQuery(name = "Customer.checkLogin", query = "SELECT c FROM Customer c WHERE c.email = :email AND c.password = :password"),
})
@Table(name = "customer", catalog = "heroku_4843a9412bf1c66", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String email;
	private String firstname;
	private String lastname;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	private Date registerDate;
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

	public Customer() {
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone,
			String zipcode, String password, Date registerDate) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.addressLine1 = address1;
		this.addressLine2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.registerDate = registerDate;
	}

	public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone,
			String zipcode, String password, Date registerDate, Set<Review> reviews, Set<BookOrder> bookOrders) {
		this(email,firstname,lastname,address1,address2,city,state,country,phone,zipcode,password,registerDate);
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	
	@Column(name = "lastname", nullable = false, length = 30)
	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	
	@Transient
	public String getFullname() {
		return this.firstname + " " + this.lastname;
	}

	@Column(name = "address_line1", nullable = false, length = 128)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String address1) {
		this.addressLine1 = address1;
	}
	
	@Column(name = "address_line2", nullable = false, length = 128)
	public String getAddressLine2() {
		return this.addressLine2;
	}
	
	public void setAddressLine2(String address2) {
		this.addressLine2 = address2;
	}

	@Column(name = "city", nullable = false, length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "state", nullable = false, length = 45)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 4)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	@Transient
	public String getCountryName() {
		return new Locale("", this.country).getDisplayCountry();
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", nullable = false, length = 24)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<BookOrder> getBookOrders() {
		return this.bookOrders;
	}

	public void setBookOrders(Set<BookOrder> bookOrders) {
		this.bookOrders = bookOrders;
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/customer/CreateCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/create_customer")
public class CreateCustomerServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
    
    public CreateCustomerServlet() {
        super();
    }

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		CustomerServices customerServices=new CustomerServices(request, response);
		customerServices.createCustomer();
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/customer/DeleteCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/delete_customer")
public class DeleteCustomerServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
     
    public DeleteCustomerServlet() {
        super();
    }
    
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    	CustomerServices customerServices = new CustomerServices(request, response);
		customerServices.deleteCustomer();
    }
}

BookStoreWebsite/src/com/bookstore/controller/admin/customer/EditCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/edit_customer")
public class EditCustomerServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
 
    public EditCustomerServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    	CustomerServices customerServices=new CustomerServices(request, response);
    	customerServices.editCustomer();
    }

}

BookStoreWebsite/WebContent/common/common_order_detail.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<div class="shadow p-3 mb-5 bg-body rounded">
	<div class="row">
		<div class="col-lg-8 col-md-7 py-2">
			<div class="d-flex flex-column">
				<h6 style="color: #0a58ca; font-size: larger;">Receipt Information</h6>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="firstname" id="firstname" class="form-control border-top-0 border-end-0 border-start-0" value="${order.firstname}" placeholder="first name" readonly="readonly" /> <label
							for="firstname">First Name</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="lastname" id="lastname" class="form-control border-top-0 border-end-0 border-start-0" value="${order.lastname}" placeholder="last name" readonly="readonly" /> <label
							for="lastname">Last Name</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="address1" id="address1" class="form-control border-top-0 border-end-0 border-start-0" value="${order.addressLine1}" placeholder="address 1" readonly="readonly" /> <label
							for="address1">Address 1</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="address2" id="address2" class="form-control border-top-0 border-end-0 border-start-0" value="${order.addressLine2}" placeholder="address 2" readonly="readonly" /> <label
							for="address2">Address 2</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<div class="d-flex">
							<div class="form-floating flex-fill">
								<input type="text" name="state" id="state" class="form-control border-top-0 border-end-0 border-start-0" value="${order.state}" placeholder="state" readonly="readonly" /> <label for="state">State</label>
							</div>
							<div class="form-floating flex-fill ms-1">
								<input type="text" name="city" id="city" class="form-control border-top-0 border-end-0 border-start-0" value="${order.city}" placeholder="city" readonly="readonly" /> <label for="city">City</label>
							</div>
						</div>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="country" id="country" class="form-control border-top-0 border-end-0 border-start-0" value="${order.countryName}" placeholder="country" readonly="readonly" /> 
						<label for="country">Country</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="number" name="phone" id="phone" class="form-control border-top-0 border-end-0 border-start-0" value="${order.phone}" placeholder="phone" readonly="readonly" /> <label for="phone">Phone
							Number</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="number" name="zipcode" id="zipcode" class="form-control border-top-0 border-end-0 border-start-0" value="${order.zipcode}" placeholder="zipcoe" readonly="readonly" /> <label
							for="zipcode">ZipCode</label>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-md-5 px-3 py-2">
			<div class="d-flex flex-column">
				<h6 style="color: #0a58ca; font-size: larger;">Order Overview</h6>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="name" id="name" class="form-control border-top-0 border-end-0 border-start-0" value="${order.customer.fullname}" placeholder="order by" readonly="readonly" /> 
						<label for="name">Order by</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="subtotal" id="subtotal" class="form-control border-top-0 border-end-0 border-start-0" value="<fmt:formatNumber value="${order.subtotal}" type="currency" maxFractionDigits = "2" currencySymbol="$" />" placeholder="subtotal" readonly="readonly" /> 
						<label for="subtotal">SubTotal</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="status" id="status" class="form-control border-top-0 border-end-0 border-start-0" value="${order.status}" placeholder="status" readonly="readonly" /> 
						<label for="status">Status</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="ship" id="ship" class="form-control border-top-0 border-end-0 border-start-0" value="<fmt:formatNumber value="${order.shippingFee}" type="currency" maxFractionDigits = "2" currencySymbol="$" />" placeholder="ship" readonly="readonly" /> 
						<label for="ship">Shipping</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="date" id="date" class="form-control border-top-0 border-end-0 border-start-0" value="<fmt:formatDate pattern="MM/dd/yyyy" value='${order.orderDate}' />" placeholder="date" readonly="readonly" /> 
						<label for="date">Date</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="tax" id="tax" class="form-control border-top-0 border-end-0 border-start-0" value="<fmt:formatNumber value="${order.tax}" type="currency" maxFractionDigits = "2" currencySymbol="$" />" placeholder="tax" readonly="readonly" /> 
						<label for="tax">Tax</label>
					</div>
				</div>
				<div class="d-flex my-2">
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="payment" id="payment" class="form-control border-top-0 border-end-0 border-start-0" value="${order.paymentMethod}" placeholder="payment" readonly="readonly" /> 
						<label for="payment">Payment</label>
					</div>
					<div class="form-floating flex-fill ms-1">
						<input type="text" name="total" id="total" class="form-control border-top-0 border-end-0 border-start-0" value="<fmt:formatNumber value="${order.total}" type="currency" maxFractionDigits = "2" currencySymbol="$" />" placeholder="total" readonly="readonly" /> 
						<label for="total">Total</label>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="table-responsive-lg shadow p-3 mb-5 bg-body rounded">
	<table class="table table-hover caption-top">
		<caption class="fs-3 text-left">
			<span>List produce of order ID: ${order.orderId}</span>
		</caption>
		<thead>
			<tr>
				<th scope="col">No</th>
				<th scope="col">Book</th>
				<th scope="col">SubTotal</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach var="orderDetail" items="${order.orderDetails}" varStatus="status">
				<tr class="py-3">
					<th scope="row">${status.index + 1}</th>
					<td>
						<div class="row g-0">
							<div class="col-md-2">
								<img class="img-fluid" width="100px" height="200px" src="data:image/jpg;base64,${orderDetail.book.base64Image}" alt="">
						    </div>
						    <div class="col-md-10">
						    	<div class="card-body">
						        	<h5 class="card-title">${orderDetail.book.title}</h5>
						        	<p class="card-text"><small class="text-muted">${orderDetail.book.author}</small></p>
						        	<div>
										<span class="text-muted"><fmt:formatNumber value="${orderDetail.book.price}" type="currency" maxFractionDigits = "2" currencySymbol="$" /></span>
										<span class="text-muted"> x ${orderDetail.quantity}</span>						        
						        	</div>
						      	</div>
						    </div>
						 </div>
					</td>
					<td><span class="text-muted"><fmt:formatNumber value="${orderDetail.subtotal}" type="currency" maxFractionDigits = "2" currencySymbol="$" /></span></td>
				</tr>
			</c:forEach>
		</tbody>
		<tfoot>
			<tr>
				<td></td>
				<td><span class="fw-bolder fs-5">Total(${order.bookCopies} item):</span></td>
				<td><span class="fw-bolder fs-5"><fmt:formatNumber value="${order.subtotal}" type="currency" maxFractionDigits = "2" currencySymbol="$" /></span></td>
			</tr>
		</tfoot>
	</table>
</div>

BookStoreWebsite/WebContent/common/customer_form.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div class="d-flex justify-content-between">
	<div class="form-floating flex-fill">
		<input type="text" name="firstName" id="firstName" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.firstname}" placeholder="First name" required /> <label
			for="firstName">First name</label>
	</div>
	<div class="form-floating ms-1 flex-fill">
		<input type="text" name="lastName" class="form-control border-top-0 border-end-0 border-start-0" id="lastName" value="${customer.lastname}" placeholder="Last name" required /> <label for="lastName">Last
			name</label>
	</div>
</div>
<div class="d-flex justify-content-between">
	<div class="form-floating flex-fill">
		<input type="text" name="address1" id="address1" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.addressLine1}" placeholder="Address line 1" required> <label
			for="address1">Address 1</label>
	</div>
	<div class="form-floating ms-1 flex-fill">
		<input type="text" name="address2" id="address2" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.addressLine2}" placeholder="Address line 2" required> <label
			for="address2">Address 2</label>
	</div>
</div>
<div class="d-flex justify-content-between">
	<div class="form-floating flex-fill">
		<input type="number" name="phone" id="phone" min="0" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.phone}" placeholder="phone number" required> <label
			for="phone">Phone number</label>
	</div>
	<div class="form-floating ms-1 flex-fill">
		<input type="number" name="zipcode" class="form-control border-top-0 border-end-0 border-start-0" id="zipcode" min="0" value="${customer.zipcode}" placeholder="Zip code" required> <label
			for="zipcode">ZipCode</label>
	</div>
</div>
<div class="d-flex justify-content-between">
	<div class="form-floating flex-fill">
		<input type="text" name="city" class="form-control border-top-0 border-end-0 border-start-0" id="city" value="${customer.city}" placeholder="City" required> <label for="city">City</label>
	</div>
	<div class="form-floating ms-1 flex-fill">
		<input type="text" name="state" id="state" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.state}" placeholder="State" required> <label for="state">State</label>
	</div>
</div>
<div class="d-flex justify-content-between">
	<div class="form-floating">
		<input type="email" name="email" id="email" class="form-control border-top-0 border-end-0 border-start-0" value="${customer.email}" placeholder="Email" required> <label for="email">Email</label>
	</div>
	<div class="form-floating ms-1">
		<select name="country" class="form-select border-top-0 border-end-0 border-start-0" id="country">
			<c:forEach items="${mapCountries}" var="country">
				<option value="${country.value}" <c:if test='${customer.country eq country.value}'>
		                                            selected='selected'</c:if>>${country.key}</option>
			</c:forEach>
		</select> 
		<label for="country">Country</label>
	</div>
</div>
<div class="d-flex justify-content-between">
	<div class="form-floating flex-fill">
		<input type="password" name="password" class="form-control border-top-0 border-end-0 border-start-0" id="password" value="${customer.password}" placeholder="Password" required> <label
			for="password">Password</label>
	</div>
	<div class="form-floating ms-1 flex-fill">
		<input type="password" name="confirmPassword" class="form-control border-top-0 border-end-0 border-start-0" id="confirmPassword" value="${customer.password}" placeholder="Confirm Password" required>
		<label for="confirmPassword">Confirm password</label>
	</div>
</div>