BookStoreWebsite/src/com/bookstore/entity/Book.java
package com.bookstore.entity;
// Generated Aug 6, 2020, 5:25:25 PM by Hibernate Tools 5.2.12.Final


import java.util.Base64;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

@Entity
@NamedQueries({
	@NamedQuery(name = "Book.findAll", query = "SELECT b FROM Book b ORDER BY b.title ASC"),
	@NamedQuery(name = "Book.findByTitle", query = "SELECT b FROM Book b WHERE b.title= :title"),
	@NamedQuery(name = "Book.countAll", query = "SELECT Count(*) FROM Book b"),
	@NamedQuery(name = "Book.countByCategory", query = "SELECT COUNT(b) FROM Book b "
						+ "WHERE b.category.categoryId = :catId"),
	@NamedQuery(name = "Book.findByCategory", query = "SELECT b FROM Book b JOIN Category c ON b.category.categoryId = c.categoryId AND c.categoryId = :categoryId"),
	@NamedQuery(name = "Book.listNew", query = "SELECT b FROM Book b ORDER BY b.publishDate DESC"),
	@NamedQuery(name = "Book.search", query = "SELECT b FROM Book b WHERE b.title LIKE '%' || :keyword || '%'"
				+ "OR b.author LIKE '%' || :keyword || '%'"
				+ "OR b.description LIKE '%' || :keyword || '%'"),
})
@Table(name="book"
    ,catalog="heroku_4843a9412bf1c66"
    , uniqueConstraints = @UniqueConstraint(columnNames="title") 
)
public class Book  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer bookId;
     private Category category;
     private String title;
     private String author;
     private String description;
     private String isbn;
     private byte[] image;
     private String base64Image;
     private float price;
     private Date publishDate;
     private Date lastUpdateTime;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Book() {
    }
	
    public Book(Integer bookId) {
		super();
		this.bookId = bookId;
	}

	public Book(Category category, String title, String author, String description, String isbn, byte[] image, float price, Date publishDate, Date lastUpdateTime) {
        this.category = category;
        this.title = title;
        this.author = author;
        this.description = description;
        this.isbn = isbn;
        this.image = image;
        this.price = price;
        this.publishDate = publishDate;
        this.lastUpdateTime = lastUpdateTime;
    }
    public Book(Category category, String title, String author, String description, String isbn, byte[] image, float price, Date publishDate, Date lastUpdateTime, Set<Review> reviews, Set<OrderDetail> orderDetails) {
       this.category = category;
       this.title = title;
       this.author = author;
       this.description = description;
       this.isbn = isbn;
       this.image = image;
       this.price = price;
       this.publishDate = publishDate;
       this.lastUpdateTime = lastUpdateTime;
       this.reviews = reviews;
       this.orderDetails = orderDetails;
    }
   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="title", unique=true, nullable=false, length=128)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="author", nullable=false, length=64)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="description", nullable=false, length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="isbn", nullable=false, length=15)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    
    @Column(name="image", nullable=false)
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    @Column(name="price", nullable=false, precision=12, scale=0)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="publish_date", nullable=false, length=10)
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update_time", nullable=false, length=19)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="book")
    public Set<Review> getReviews() {
    	TreeSet<Review> sortedReviews=new TreeSet<Review>(new Comparator<Review>() {

			@Override
			public int compare(Review review1, Review review2) {
				return review2.getReviewTime().compareTo(review1.getReviewTime());
			}
		});
    	
    	sortedReviews.addAll(reviews);
        return sortedReviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="book")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    @Transient
	public String getBase64Image() {
		this.base64Image=Base64.getEncoder().encodeToString(this.image);
		return base64Image;
	}

    @Transient
	public void setBase64Image(String base64Image) {
		this.base64Image = base64Image;
	}

    @Transient
	public float getAverageRating () {
    	float averageRating=0.0f;
    	float sum=0.0f;
    	
    	if (reviews.isEmpty()) {
			return 0.0f;
		}
    	
    	for (Review review : reviews) {
			sum+=review.getRating();
		}
    	
    	averageRating= sum/reviews.size();
    	return averageRating;
    }
    
    @Transient
	public String getRatingStars() {
    	float averageRating=getAverageRating();
    	return getRatingString(averageRating);
    }
    
    @Transient
	public String getRatingString (float averageRating) {
    	String result = "";
    	int numberOfStartOn=(int) averageRating;
    	
    	for (int i = 1; i <= numberOfStartOn; i++) {
			result += "on,";
		}
    	
    	int next = numberOfStartOn + 1; 
    	if (averageRating > numberOfStartOn) {
			result += "half,";
			next++;
		}
    	
    	for (int j = next; j <= 5; j++) {
			result += "off,";
		}
    	
    	return result.substring(0, result.length()-1);
    }
    
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookId == null) ? 0 : bookId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Book other = (Book) obj;
		if (bookId == null) {
			if (other.bookId != null)
				return false;
		} else if (!bookId.equals(other.bookId))
			return false;
		return true;
	}
 
}

BookStoreWebsite/src/com/bookstore/entity/Review.java
package com.bookstore.entity;
// default package

// Generated Sep 2, 2020, 8:57:07 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.NamedQueries;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@NamedQueries({ 
	@NamedQuery(name = "Review.listAll", query = "SELECT r FROM Review r ORDER BY r.reviewTime DESC"),
	@NamedQuery(name = "Review.countAll", query = "SELECT COUNT(r) FROM Review r"), 
	@NamedQuery(name = "Review.findByCustomerAndBook", query = "SELECT r FROM Review r WHERE r.customer.customerId =: customerId"
				+ " AND r.book.bookId =: bookId"), 
	@NamedQuery(name = "Review.mostFavoreBooks", 
			query = "SELECT r.book, COUNT(r.book.bookId) AS ReviewCount, AVG(r.rating) AS AvgRating FROM Review r"
					+ " GROUP BY r.book.bookId HAVING AVG(r.rating) >= 4.0"
					+ " ORDER BY ReviewCount DESC, AvgRating DESC"),
	@NamedQuery(name = "Review.reviewCount", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId"),
	@NamedQuery(name = "Review.reviewCount5", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId AND r.rating=5"),
	@NamedQuery(name = "Review.reviewCount4", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId AND r.rating=4"),
	@NamedQuery(name = "Review.reviewCount3", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId AND r.rating=3"),
	@NamedQuery(name = "Review.reviewCount2", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId AND r.rating=2"),
	@NamedQuery(name = "Review.reviewCount1", query = "SELECT COUNT(*) FROM Review r WHERE r.book.bookId =: bookId AND r.rating=1"),
	@NamedQuery(name = "Review.countByCustomer", query = "SELECT COUNT(r.reviewId) FROM Review r WHERE r.customer.customerId =:customerId")
})
@Table(name = "review", catalog = "heroku_4843a9412bf1c66")
public class Review implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer reviewId;
	private Book book;
	private Customer customer;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Review() {
	}

	public Review(Book book, Customer customer, int rating, String headline, String comment, Date reviewTime) {
		this.book = book;
		this.customer = customer;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 128)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	
	@Transient
	public String getStars() {
		String result = "";
		int numberOfStartOn = (int) rating;

		for (int i = 1; i <= numberOfStartOn; i++) {
			result += "on,";
		}

		for (int j = numberOfStartOn + 1; j <= 5; j++) {
			result += "off,";
		}

		return result.substring(0, result.length() - 1);
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/review/DeleteReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/delete_review")
public class DeleteReviewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
     
    public DeleteReviewServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		ReviewServices reviewServices = new ReviewServices(request, response);
		reviewServices.deleteReview();
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/review/EditReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/edit_review")
public class EditReviewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
     
    public EditReviewServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		ReviewServices reviewServices=new ReviewServices(request, response);
		reviewServices.editReview();
	}

}

BookStoreWebsite/src/com/bookstore/controller/admin/review/ListReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/list_reviews")
public class ListReviewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
      
    public ListReviewServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    	ReviewServices reviewServices=new ReviewServices(request, response);
    	reviewServices.listAllReview();
    }

}

BookStoreWebsite/src/com/bookstore/controller/admin/review/UpdateReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/update_review")
public class UpdateReviewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
    
    public UpdateReviewServlet() {
        super();
    }

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		ReviewServices reviewServices = new ReviewServices(request, response);
		reviewServices.updateReview();
	}

}

BookStoreWebsite/src/com/bookstore/controller/frontend/ShowCustomerProfileServlet.java
package com.bookstore.controller.frontend;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/view_profile")
public class ShowCustomerProfileServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    public ShowCustomerProfileServlet() {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		CustomerServices customerServices=new CustomerServices(request, response);
		customerServices.showCustomerProfile();
	}

}

BookStoreWebsite/WebContent/frontend/book_detail.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>${book.title}</title>
<link rel="icon" href="images/favicon.ico">
<!-- bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/shishirraven/animate-on-scroll@v1.2/animation_utility.css">
<link rel="stylesheet" href="css/styles.css">
<!-- google font -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;900&family=Ubuntu:wght@300;400;700&display=swap" rel="stylesheet">
<!-- font Awesome -->
<script src="https://kit.fontawesome.com/c65095b9a1.js"></script>
<!-- bootstrapcdn -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- animation -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/shishirraven/animate-on-scroll@v1.0/oyethemes_onscroll_animation.js"></script>
</head>
<body>
	<jsp:include page="header.jsp"></jsp:include>
	<section class="section-2" id="features">
		<div class="bg-blue">
			<div class="container2 py-5">
				<div class="card mt-5 pt-3">
					<div class="row row-cols-1 row-cols-md-2 g-0 mb-5 pb-5">
						<div class="col-12 col-lg-4">
							<img class="img1" alt="imageBook" src="data:image/jpg;base64,${book.base64Image}" class="img-fluid" style="max-width: 323px;" />
						</div>
						<div class="col-lg-8">
							<div class="card-body text-start">
								<h3 class="card-title">${book.title}</h3>
								<span class="card-text">
									<small class="text-muted">by ${book.author} (author)</small>
								</span>

								<div class="py-3">
										<span class="book-ratting me-3"> 
											<jsp:directive.include file="book_rating.jsp" />
										</span>
										<span><a href="#review">${fn:length(book.reviews)} ratings</a></span>
								</div>

								<div class="d-flex justify-content-between pb-3">
									<h1 class="card-title pricing-card-title">
										<fmt:formatNumber value="${book.price}" type="currency" maxFractionDigits = "2" currencySymbol="$" />
									</h1>

									<button
										class="btn btn-warning fas fa-shopping-cart mt-2 mb-2 fs-5"
										id="btn_addToCart">
										&emsp;<span>Add to Cart</span>
									</button>
								</div>
								<div class="book-description">
									<div class="descript">
										<p>${book.description}</p>
									</div>
									<i class="fas fa-chevron-left pe-2"></i> 
									<a href="javascript:void();" class="item_col readMore-btn">read more</a>
								</div>
							</div>
						</div>
					</div>

					<div class="" id="review">
						<div class="">
							<h2 class="">Customer Reviews</h2>
							<div>
								<span class="fs-4 pe-3"> 
									<jsp:directive.include file="book_rating.jsp" />
								</span> 
								<span class="">
									<a href="">${fn:length(book.reviews)} customer ratings</a>
								</span>
							</div>
							
							<div class="py-5">
								<div class="row">
									<div class="col">
										<a href="">5 star</a>
									</div>
									<div class="col-6">
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar"
												aria-valuenow="${rating5}" aria-valuemin="0"
												aria-valuemax="100">
											</div>
										</div>
									</div>
									<div class="col">
										<a href=""> ${rating5}%</a> 
									</div>
								</div>
								
								<div class="row">
									<div class="col">
										<a href="">4 star</a>
									</div>
									<div class="col-6">
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar"
												aria-valuenow="${rating4}" aria-valuemin="0"
												aria-valuemax="100">
											</div>
										</div>
									</div>
									<div class="col">
										<a href=""> ${rating4}%</a>  
									</div>
								</div>
								
								<div class="row">
									<div class="col">
										<a href="">3 star</a>
									</div>
									<div class="col-6">
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar"
												aria-valuenow="${rating3}" aria-valuemin="0"
												aria-valuemax="100">
											</div>
										</div>
									</div>
									<div class="col">
										<a href=""> ${rating3}%</a>  
									</div>
								</div>
								
								<div class="row">
									<div class="col">
										<a href="">2 star</a>
									</div>
									<div class="col-6">
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar"
												aria-valuenow="${rating2}" aria-valuemin="0"
												aria-valuemax="100">
											</div>
										</div>
									</div>
									<div class="col">
										<a href=""> ${rating2}%</a>   
									</div>
								</div>
								
								<div class="row">
									<div class="col">
										<a href="">1 star</a>
									</div>
									<div class="col-6">
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar"
												aria-valuenow="${rating1}" aria-valuemin="0"
												aria-valuemax="100">
											</div>
										</div>
									</div>
									<div class="col">
										<a href=""> ${rating1}%</a>   
									</div>
								</div>
							</div>

							<div class="py-5">
								<h4>Review this product</h4>
								<p>Share your thoughts with other customers</p>
								<button type="button" class="btn btn-secondary" id="btn_writeRevie">Write a customer review</button>
							</div>
						</div>
						<div class="my-3 p-3 bg-body rounded shadow-sm">
							<c:forEach items="${book.reviews}" var="review">
							    <div class="d-flex text-muted pt-3 text-start">
							    	<img width="50" height="50" class="img" src="images/iconuser.png" alt="">
							 
								    <div class="pb-3 mb-0 small lh-sm border-bottom ps-3">
								       <strong class="d-block text-gray-dark py-2">${review.customer.fullname}</strong>
								       <div class="">
									       <div class="rating py-2">
												<c:forTokens items="${review.stars}" delims="," var="star">
													<c:if test="${star eq 'on'}">
														<img alt="stars" src="images/rating_on.png">
													</c:if>
													<c:if test="${star eq 'off'}">
														<img alt="stars" src="images/rating_off.png">
													</c:if>
												</c:forTokens>
											</div>
											<span class="py-2">Review on ${review.reviewTime}</span>
								        </div>
										<div class="py-2">
											<span>${review.headline}</span>
										</div>
										<div class="py-2">
									        <span class="item_row review-content">${review.comment}</span>
										</div>
								      </div>
							    </div>
							</c:forEach>
						</div>
					</div>
				</div>
				<!--end page main-->
			</div>
		</div>
	</section>

	<jsp:include page="footer.jsp"></jsp:include>

	<script type="text/javascript">
		/*---start read more and less---*/
		$(".readMore-btn").on('click',function() {
			$(this).parent().toggleClass("showContent");
			var replaceText;
			if ($(this).parent().hasClass("showContent")) {
				replaceText = "read less";
				$('.book-description .fa-chevron-left')
						.removeClass('fa-chevron-left')
						.addClass('fa-chevron-right');
			} else {
				replaceText = "read more";
				$('.book-description .fa-chevron-right').removeClass('fa-chevron-right').addClass('fa-chevron-left');
			}
							//var replaceText = $(this).parent().hasClass("showContent") ? "read less" : "read more";
			$(this).text(replaceText);

		});

		$(".calculated-btn").on('click',function() {
			$(this).parent().toggleClass("showContent");
			if ($(this).parent().hasClass("showContent")) {
				$('.ratting-detail .fa-chevron-down').removeClass('fa-chevron-down').addClass('fa-chevron-up');
			} else {
				$('.ratting-detail .fa-chevron-up').removeClass('fa-chevron-up').addClass('fa-chevron-down');
			}
					//var replaceText = $(this).parent().hasClass("showContent") ? "read less" : "read more";
		});
		/*---end read more and less---*/

		$(document).ready(function() {
			$("#btn_addToCart").click(function() {
				window.location = 'add_to_cart?book_id=' + ${book.bookId};
			});

			$("#btn_writeRevie").click(function() {
				window.location = 'write_review?book_id=' + ${book.bookId};
			});

			$(window).on("load", function(){
				$(window).scrollTop($('#features').position().top);
	        });
		});
	</script>
	<script src="js/rating.js"></script>
</body>
</html>

BookStoreWebsite/WebContent/frontend/book_rating.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:forTokens items="${book.ratingStars}" delims="," var="star">
	<c:if test="${star eq 'on'}">
		<img alt="stars" src="images/rating_on.png">
	</c:if>
	<c:if test="${star eq 'off'}">
		<img alt="stars" src="images/rating_off.png">
	</c:if>
	<c:if test="${star eq 'half'}">
		<img alt="stars" src="images/rating_half.png">
	</c:if>
</c:forTokens>